# Generated by Django 3.2 on 2023-06-16 20:26

from django.db import migrations


def fill_new_building_fields(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gt=2014).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


def fill_new_building_fields_backward(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.all().update(new_building=None)


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(
            fill_new_building_fields, fill_new_building_fields_backward
        )
    ]
