# Generated by Django 3.2 on 2023-06-16 21:27
import phonenumbers

from django.db import migrations


def get_owner_pure_number(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()

    for flat in flats:
        owner_pure_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(owner_pure_number):
            flat.owners_pure_number = owner_pure_number
            flat.save()


def get_owner_pure_number_backward(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.all().update(owners_pure_number=None)


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_flat_owners_pure_number"),
    ]

    operations = [
        migrations.RunPython(
            get_owner_pure_number, get_owner_pure_number_backward
        )
    ]
