# Generated by Django 3.2 on 2023-06-20 14:26

from django.db import migrations


def fill_owners_fields(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            fullname=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_number=flat.owners_pure_number,
        )


def fill_owners_fields_backwards(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    Owner.objects.all().update(
        fullname=None, phonenumber=None, pure_number=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_owner"),
    ]

    operations = [
        migrations.RunPython(
            fill_owners_fields,
            fill_owners_fields_backwards,
        )
    ]
