# Generated by Django 3.2 on 2023-06-24 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_auto_20230624_2351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owners_phonenumber",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owners_pure_number",
        ),
    ]
